SecDebugLog debug.log
SecDebugLogLevel 3

SecRuleEngine On

# ensure each transaction executes @inspectFile
SecRule ARGS:foo "@inspectFile ./inspectfile_helper.sh" "id:101,phase:2,pass,nolog,noauditlog,t:none"
