/*
 * ModSecurity, http://www.modsecurity.org/
 * Copyright (c) 2015 - 2021 Trustwave Holdings, Inc. (http://www.trustwave.com/)
 *
 * You may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * If any of the files related to licensing are missing or if you have any
 * other questions related to licensing please contact Trustwave Holdings, Inc.
 * directly using the email address security@modsecurity.org.
 *
 */

#include "html_entity_decode.h"

#include <cstring>

#include "src/utils/string.h"

#ifdef WIN32
#include "src/compat/msvc.h"
#endif

using namespace modsecurity::utils::string;

namespace modsecurity::actions::transformations {


namespace {

struct NamedEntity {
    const char *name;
    std::size_t len;
    unsigned char ch;
};

/* Named-entity table for t:htmlEntityDecode.
 *
 * Compared case-insensitively against the full extracted token; the length
 * must match exactly.  Prior implementations used strncasecmp() with the name
 * length only, which caused prefix collisions (e.g. "&ltest;" decoded to "<"
 * and dropped "est").  See GHSA-cxqf-vgrr-xxrv.
 *
 * The contents below are generated, not hand-curated: a hand-written list
 * drifts from the specification (it is how &lcub;, &excl; and &Hat; came to
 * be missing while &caret;, &hyphen; and &tilde; were mapped to ASCII
 * characters the specification does not assign them).  Regenerate with:
 *
 *     curl -sSO https://html.spec.whatwg.org/entities.json
 *     python3 tools/gen-html-entities.py entities.json
 *
 * NAMED_ENTITY derives the name length from the string literal at compile
 * time so the two cannot drift out of sync.
 */
#define NAMED_ENTITY(name_lit, character) \
    { (name_lit), sizeof(name_lit) - 1, static_cast<unsigned char>(character) }

constexpr NamedEntity named_entities[] = {
    /* Generated by tools/gen-html-entities.py from
     * https://html.spec.whatwg.org/entities.json -- do not edit by hand.
     *
     * Every entity expanding to a single code point in U+0000..U+007F,
     * plus NBSP (U+00A0) and SOFT HYPHEN (U+00AD).  44 entries.
     *
     * Case-insensitive matching collapses these spec distinctions:
     *   &GT; = U+003E wins over &Gt; = U+226B
     *   &LT; = U+003C wins over &Lt; = U+226A
     *   &colon; = U+003A wins over &Colon; = U+2237
     *   &verbar; = U+007C wins over &Verbar; = U+2016
     *   &vert; = U+007C wins over &Vert; = U+2016
     */
    NAMED_ENTITY("amp",              '&'),
    NAMED_ENTITY("apos",             '\''),
    NAMED_ENTITY("ast",              '*'),
    NAMED_ENTITY("bsol",             '\\'),
    NAMED_ENTITY("colon",            ':'),
    NAMED_ENTITY("comma",            ','),
    NAMED_ENTITY("commat",           '@'),
    NAMED_ENTITY("diacriticalgrave", '`'),
    NAMED_ENTITY("dollar",           '$'),
    NAMED_ENTITY("equals",           '='),
    NAMED_ENTITY("excl",             '!'),
    NAMED_ENTITY("grave",            '`'),
    NAMED_ENTITY("gt",               '>'),
    NAMED_ENTITY("hat",              '^'),
    NAMED_ENTITY("lbrace",           '{'),
    NAMED_ENTITY("lbrack",           '['),
    NAMED_ENTITY("lcub",             '{'),
    NAMED_ENTITY("lowbar",           '_'),
    NAMED_ENTITY("lpar",             '('),
    NAMED_ENTITY("lsqb",             '['),
    NAMED_ENTITY("lt",               '<'),
    NAMED_ENTITY("midast",           '*'),
    NAMED_ENTITY("nbsp",             NBSP),
    NAMED_ENTITY("newline",          '\n'),
    NAMED_ENTITY("nonbreakingspace", NBSP),
    NAMED_ENTITY("num",              '#'),
    NAMED_ENTITY("percnt",           '%'),
    NAMED_ENTITY("period",           '.'),
    NAMED_ENTITY("plus",             '+'),
    NAMED_ENTITY("quest",            '?'),
    NAMED_ENTITY("quot",             '\"'),
    NAMED_ENTITY("rbrace",           '}'),
    NAMED_ENTITY("rbrack",           ']'),
    NAMED_ENTITY("rcub",             '}'),
    NAMED_ENTITY("rpar",             ')'),
    NAMED_ENTITY("rsqb",             ']'),
    NAMED_ENTITY("semi",             ';'),
    NAMED_ENTITY("shy",              0xAD),
    NAMED_ENTITY("sol",              '/'),
    NAMED_ENTITY("tab",              '\t'),
    NAMED_ENTITY("underbar",         '_'),
    NAMED_ENTITY("verbar",           '|'),
    NAMED_ENTITY("vert",             '|'),
    NAMED_ENTITY("verticalline",     '|'),
};

#undef NAMED_ENTITY

bool lookup_named_entity(const unsigned char *name, std::size_t name_len,
                         unsigned char *out) {
    for (const auto &e : named_entities) {
        if (e.len == name_len &&
            strncasecmp(reinterpret_cast<const char *>(name), e.name,
                        name_len) == 0) {
            *out = e.ch;
            return true;
        }
    }
    return false;
}

}  // namespace


static inline bool inplace(std::string &value) {
    const auto input_len = value.length();
    auto d = reinterpret_cast<unsigned char*>(value.data());
    const unsigned char *input = d;
    const unsigned char *end = input + input_len;

    std::string::size_type i = 0;
    while (i < input_len) {
        std::string::size_type copy = 1;

        /* Require an ampersand and at least one character to
         * start looking into the entity.
         */
        if ((input[i] == '&') && (i + 1 < input_len)) {
            auto j = i + 1;

            if (input[j] == '#') {
                /* Numerical entity. */
                copy++;

                if (!(j + 1 < input_len)) {
                    goto HTML_ENT_OUT; /* Not enough bytes. */
                }
                j++;

                if ((input[j] == 'x') || (input[j] == 'X')) {
                    /* Hexadecimal entity. */
                    copy++;

                    if (!(j + 1 < input_len)) {
                        goto HTML_ENT_OUT; /* Not enough bytes. */
                    }
                    j++; /* j is the position of the first digit now. */

                    auto k = j;
                    while ((j < input_len) && (isxdigit(input[j]))) {
                        j++;
                    }
                    if (j > k) { /* Do we have at least one digit? */
                        /* Decode the entity. */
                        char *x = new char[(j - k) + 1];
                        std::copy(input + k, input + j, x);
                        x[j - k] = '\0';

                        *d++ = (unsigned char)strtol(x, nullptr, 16);
                        delete[] x;

                        /* Skip over the semicolon if it's there. */
                        if ((j < input_len) && (input[j] == ';')) {
                            i = j + 1;
                        } else {
                            i = j;
                        }
                        continue;
                    } else {
                        goto HTML_ENT_OUT;
                    }
                } else {
                    /* Decimal entity. */
                    auto k = j;

                    while ((j < input_len) && (isdigit(input[j]))) {
                        j++;
                    }
                    if (j > k) { /* Do we have at least one digit? */
                        /* Decode the entity. */
                        char *x = new char[j - k + 1];
                        std::copy(input + k, input + j, x);

                        x[j - k] = '\0';
                        *d++ = (unsigned char)strtol(x, nullptr, 10);
                        delete[] x;

                        /* Skip over the semicolon if it's there. */
                        if ((j < input_len) && (input[j] == ';')) {
                            i = j + 1;
                        } else {
                            i = j;
                        }
                        continue;
                    } else {
                        goto HTML_ENT_OUT;
                    }
                }
            } else {
                /* Text entity. */
                auto k = j;
                while ((j < input_len) && (isalnum(input[j]))) {
                    j++;
                }
                if (j > k) { /* Do we have at least one character? */
                    unsigned char decoded = 0;
                    if (!lookup_named_entity(&input[k], j - k, &decoded)) {
                        /* Unknown entity: copy the raw data over. */
                        copy = j - k + 1;
                        goto HTML_ENT_OUT;
                    }
                    *d++ = decoded;

                    /* Skip over the semicolon if it's there. */
                    if ((j < input_len) && (input[j] == ';')) {
                        i = j + 1;
                    } else {
                        i = j;
                    }

                    continue;
                }
            }
        }

HTML_ENT_OUT:

        for (std::string::size_type z = 0; z < copy; z++) {
            *d++ = input[i++];
        }
    }

    *d = '\0';

    value.resize(d - input);
    return d != end;
}


bool HtmlEntityDecode::transform(std::string &value, const Transaction *trans) const {
    return inplace(value);
}


}  // namespace modsecurity::actions::transformations
