/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_modsecurity_ModSecurity */

#ifndef _Included_org_modsecurity_ModSecurity
#define _Included_org_modsecurity_ModSecurity
#ifdef __cplusplus
extern "C" {
#endif
#undef org_modsecurity_ModSecurity_DONE
#define org_modsecurity_ModSecurity_DONE -2L
#undef org_modsecurity_ModSecurity_DECLINED
#define org_modsecurity_ModSecurity_DECLINED -1L
#undef org_modsecurity_ModSecurity_OK
#define org_modsecurity_ModSecurity_OK 0L
/*
 * Class:     org_modsecurity_ModSecurity
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_modsecurity_ModSecurity_initialize
  (JNIEnv *, jobject);

/*
 * Class:     org_modsecurity_ModSecurity
 * Method:    destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_modsecurity_ModSecurity_destroy
  (JNIEnv *, jobject);

/*
 * Class:     org_modsecurity_ModSecurity
 * Method:    onRequest
 * Signature: (Ljava/lang/String;Lorg/modsecurity/MsHttpTransaction;Z)I
 */
JNIEXPORT jint JNICALL Java_org_modsecurity_ModSecurity_onRequest
  (JNIEnv *, jobject, jstring, jobject, jboolean);

/*
 * Class:     org_modsecurity_ModSecurity
 * Method:    onResponse
 * Signature: (Lorg/modsecurity/MsHttpTransaction;)I
 */
JNIEXPORT jint JNICALL Java_org_modsecurity_ModSecurity_onResponse
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
