#!/usr/bin/env python3
"""Generate the named-entity table used by t:htmlEntityDecode.

Source of truth is the WHATWG named character reference list:

    https://html.spec.whatwg.org/entities.json

Selection rule: every entity whose expansion is a single code point that a
rule could plausibly need to see as an ASCII byte -- U+0000..U+007F, plus
U+00A0 (NBSP, which the decoder has always emitted) and U+00AD (SOFT HYPHEN,
which browsers strip from URLs).  Entities expanding to more than one code
point, or to anything outside that set, are deliberately excluded: the
decoder emits one byte per entity.

Matching in the decoder is case-insensitive, which the spec is not.  Where
two spec entities differ only by case and disagree on the code point (e.g.
&colon; = U+003A but &Colon; = U+2237), the ASCII one wins and the collision
is listed in the generated header comment.

Usage:
    curl -sSO https://html.spec.whatwg.org/entities.json
    python3 tools/gen-html-entities.py entities.json
"""
import json
import sys
from collections import defaultdict

WANTED = lambda cp: cp < 0x80 or cp in (0xA0, 0xAD)
NAMES = {0xA0: "NBSP", 0xAD: "0xAD"}
ESCAPES = {0x09: r"'\t'", 0x0A: r"'\n'", 0x0D: r"'\r'", 0x22: r"'\"'",
           0x27: r"'\''", 0x5C: r"'\\'", 0x00: r"'\0'"}


def literal(cp):
    if cp in NAMES:
        return NAMES[cp]
    if cp in ESCAPES:
        return ESCAPES[cp]
    if 0x20 < cp < 0x7F:
        return "'%s'" % chr(cp)
    return "0x%02x" % cp


def main(path):
    entities = json.load(open(path))
    by_lower = defaultdict(dict)
    for name, spec in entities.items():
        if not name.endswith(";"):
            continue                       # legacy semicolon-less forms
        points = spec["codepoints"]
        if len(points) != 1:
            continue
        by_lower[name.strip("&;").lower()][name.strip("&;")] = points[0]

    table, collisions = {}, []
    for lower, variants in by_lower.items():
        wanted = {n: cp for n, cp in variants.items() if WANTED(cp)}
        if not wanted:
            continue
        chosen = sorted(set(wanted.values()))[0]
        if len(set(variants.values())) > 1:
            other = sorted(f"&{n}; = U+{cp:04X}" for n, cp in variants.items()
                           if cp != chosen)
            collisions.append("&%s; = U+%04X wins over %s" %
                              (sorted(wanted)[0], chosen, ", ".join(other)))
        table[lower] = chosen

    width = max(len(n) for n in table) + 3
    print("/* Generated by tools/gen-html-entities.py from")
    print(" * https://html.spec.whatwg.org/entities.json -- do not edit by hand.")
    print(" *")
    print(" * Every entity expanding to a single code point in U+0000..U+007F,")
    print(" * plus NBSP (U+00A0) and SOFT HYPHEN (U+00AD).  %d entries." % len(table))
    if collisions:
        print(" *")
        print(" * Case-insensitive matching collapses these spec distinctions:")
        for c in sorted(collisions):
            print(" *   %s" % c)
    print(" */")
    for name in sorted(table):
        print('    NAMED_ENTITY("%s",%s%s),' %
              (name, " " * (width - len(name) - 2), literal(table[name])))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "entities.json")
