name: Quality Assurance

on:
  push:
  pull_request:

jobs:
  build-linux:
    name: Linux (${{ matrix.platform.label }}, ${{ matrix.compiler.label }}, ${{ matrix.configure.label }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        platform:
          - {label: "x64", arch: "amd64", configure: ""}
          - {label: "x32", arch: "i386", configure: "PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32"}
        compiler:
          - {label: "gcc", cc: "gcc", cxx: "g++"}
          - {label: "clang", cc: "clang", cxx: "clang++"}
        configure:
          - {label: "with parser generation", opt: "--enable-parser-generation" }
          - {label: "wo curl",    opt: "--without-curl" }
          - {label: "wo lua",     opt: "--without-lua" }
          - {label: "wo maxmind", opt: "--without-maxmind" }
          - {label: "wo libxml",  opt: "--without-libxml" }
          - {label: "wo geoip",   opt: "--without-geoip" }
          - {label: "wo ssdeep",  opt: "--without-ssdeep" }
          - {label: "with lmdb",  opt: "--with-lmdb" }
          - {label: "with pcre", opt: "--with-pcre" }
        exclude:
          - platform: {label: "x32"}
            configure: {label: "wo geoip"}
          - platform: {label: "x32"}
            configure: {label: "wo ssdeep"}
    steps:
      - name: Setup Dependencies (common)
        run: |
          sudo dpkg --add-architecture ${{ matrix.platform.arch }}
          sudo apt-get update -y -qq
          sudo apt-get install -y libyajl-dev:${{ matrix.platform.arch }} \
                                  libcurl4-openssl-dev:${{ matrix.platform.arch }} \
                                  liblmdb-dev:${{ matrix.platform.arch }} \
                                  liblua5.2-dev:${{ matrix.platform.arch }} \
                                  libmaxminddb-dev:${{ matrix.platform.arch }} \
                                  libpcre2-dev:${{ matrix.platform.arch }} \
                                  pcre2-utils:${{ matrix.platform.arch }} \
                                  bison flex
      - name: Setup Dependencies (x32)
        if: ${{ matrix.platform.label == 'x32' }}
        run: |
          sudo apt-get install g++-multilib
          sudo apt-get install -y libxml2-dev:${{ matrix.platform.arch }} \
                                  libpcre3-dev:${{ matrix.platform.arch }}
      - name: Setup Dependencies (x64)
        if: ${{ matrix.platform.label == 'x64' }}
        run: |
          sudo apt-get install -y libgeoip-dev:${{ matrix.platform.arch }} \
                                  libfuzzy-dev:${{ matrix.platform.arch }}
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - name: Init git submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --force
      - name: build.sh
        run: ./build.sh
      - name: configure
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: ./configure ${{ matrix.platform.configure }} ${{ matrix.configure.opt }} --enable-assertions=yes
      - uses: ammaraskar/gcc-problem-matcher@master
      - name: make
        run: make -j `nproc`
      - name: check
        run: make check

  build-macos:
    name: macOS (${{ matrix.configure.label }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        configure:
          - {label: "with parser generation", opt: "--enable-parser-generation" }
          - {label: "wo curl",    opt: "--without-curl" }
          - {label: "wo lua",     opt: "--without-lua" }
          - {label: "wo maxmind", opt: "--without-maxmind" }
          - {label: "wo libxml",  opt: "--without-libxml" }
          - {label: "wo geoip",   opt: "--without-geoip" }
          - {label: "wo ssdeep",  opt: "--without-ssdeep" }
          - {label: "with lmdb",  opt: "--with-lmdb" }
          - {label: "with pcre", opt: "--with-pcre" }
    steps:
      - name: Setup Homebrew
        run: |
          echo "PATH=/opt/homebrew/bin:$PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig:/opt/homebrew/opt/openssl/lib/pkgconfig:/opt/homebrew/opt/pcre/lib/pkgconfig:/opt/homebrew/opt/pcre2/lib/pkgconfig:/opt/homebrew/opt/libxml2/lib/pkgconfig:/opt/homebrew/opt/curl/lib/pkgconfig:/opt/homebrew/opt/icu4c/lib/pkgconfig:/opt/homebrew/opt/openssl@3/lib/pkgconfig" >> $GITHUB_ENV
      - name: Install Dependencies
        run: |
          brew update
          brew install \
                       yajl \
                       lmdb \
                       lua@5.2 \
                       libmaxminddb \
                       pcre2 \
                       geoip \
                       ssdeep \
                       pcre \
                       bison \
                       flex
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - name: Init git submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --force
      - name: Build GeoIP
        run: |
          git clone --depth 1 --no-checkout https://github.com/maxmind/geoip-api-c.git
          cd geoip-api-c
          git fetch --tags
          # Check out the last release, v1.6.12
          git checkout 4b526e7331ca1d692b74a0509ddcc725622ed31a
          autoreconf --install
          ./configure --disable-dependency-tracking --disable-silent-rules --prefix=/opt/homebrew
          make install
      - name: build.sh
        run: ./build.sh
      - name: configure
        run: ./configure ${{ matrix.configure.opt }} --enable-assertions=yes
      - uses: ammaraskar/gcc-problem-matcher@master
      - name: make
        run: make -j `sysctl -n hw.logicalcpu`
      - name: check
        run: make check

  build-windows:
    name: Windows (${{ matrix.configure.label }})
    runs-on: windows-latest
    strategy:
      matrix:
        configure:
          - {label: "default", opt: "" }
          - {label: "wo curl",    opt: "-DWITH_CURL=OFF" }
          - {label: "wo lua",     opt: "-DWITH_LUA=OFF" }
          - {label: "wo maxmind", opt: "-DWITH_MAXMIND=OFF" }
          - {label: "wo libxml",  opt: "-DWITH_LIBXML2=OFF" }
          - {label: "with lmdb",  opt: "-DWITH_LMDB=ON" }
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - name: Init git submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --force
      - name: Install Conan
        run: |
          pip3 install conan
      - name: Configure Conan
        run: |
          conan profile detect
      - name: Configure CMake
        run: |
          cmake -S . -B build ${{ matrix.configure.opt }}
      - name: Build
        run: |
          cmake --build build --config Release

  cppcheck-linux:
    name: cppcheck (Linux)
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y \
            cppcheck \
            autoconf \
            automake \
            libtool
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - name: Init git submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --force
      - name: configure
        run: |
          ./build.sh
          ./configure
      - name: cppcheck
        run: make check-static

  cppcheck-macos:
    name: cppcheck (macOS)
    runs-on: macos-14
    steps:
      - name: Setup Dependencies
        # curl, pcre2 not installed because they're from Apple
        run: |
          brew update
          brew install autoconf \
                       automake \
                       libtool \
                       cppcheck
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - name: Init git submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --force
      - name: configure
        run: |
          ./build.sh
          ./configure
      - name: cppcheck
        run: make check-static
