name: OSV Scanner (PR)

on:
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  scan-pr:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@375a0e8ebdc98e99b02ac4338a724f5750f21213

