name: OSSF Scorecard

on:
  workflow_dispatch:
  branch_protection_rule:
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: "10 1 * * 0"

permissions:
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      issues: read
      pull-requests: read
      checks: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          persist-credentials: false

      - name: Run Scorecard
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: false

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: scorecard.sarif
          category: scorecard
